import { MessageSuccess } from "@/components/MessageSucces"
import Head from "next/head"

export default function Success() {
  return (
    <>
      <Head>
        <title>Your message was a success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MessageSuccess />
    </>
  )
}
